// ==UserScript==
// @name         VK Pixel bot
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  Make VK Great again
// @author       F6CF
// @match        https://pixel.vkforms.ru/*
// @grant        none
// ==/UserScript==

function Bot(){window.Bot=Bot;Bot.pts=30;Bot.tc="rgb(0, 0, 0)";Bot.src="https://raw.githubusercontent.com/Creeplays/Temp/master/VKIMG.png";Bot.state=document.createElement("div");Bot.state.textContent="Loading bot";Object.assign(Bot.state.style,{background:"rgb(128, 128, 128)",bottom:"0px",right:"0px",width:"100%",height:"51px",lineHeight:"50px",textAlign:"center",color:"rgb(72, 61, 139)",position:"fixed",fontSize:"2em",fontWeight:"bold",zIndex:1E4});document.body.appendChild(Bot.state);Bot.setState=
function(a){Bot.state.innerHTML="SpaceVK "+a;console.log("SpaceVK "+a)};Bot.reloadImage=function(){Bot.img=new Image;Bot.img.crossOrigin="Anonymous";Bot.img.onload=function(){Bot.setState("Reload");Bot.inited&&Bot.getFullData()};Bot.img.src=Bot.src+"?r="+Math.random()};Bot.canvasEvent=function(a,b){Bot.canvas&&("mousewheel"==a?Bot.canvas.dispatchEvent(new WheelEvent("mousewheel",b)):Bot.canvas.dispatchEvent(new MouseEvent(a,b)))};Bot.canvasClick=function(a,b,d){var e=a+0;Bot.resetZoom();795<a?(Bot.canvasMoveTo(795,
0),a-=795):Bot.canvasMoveTo(0,0);var c={bubbles:!0,cancelable:!0,button:1,clientX:a,clientY:b+1,layerX:a,layerY:b+1};a=Bot.getColor(Bot.ctx.getImageData(a,b+1,1,1).data,0);var f=document.querySelector('[style="background-color: '+d+';"]');f?a==d?Bot.setState("Skip "+(e+1)+"x"+(b+1)):(Bot.setState("Point at "+(e+1)+"x"+(b+1)),f.click(),Bot.canvasEvent("mousedown",c),Bot.canvasEvent("click",c),c.button=0,Bot.canvasEvent("mouseup",c),document.querySelector(".App__confirm button").click()):Bot.setState("Color not in palette ")};
Bot.draw=function(){if(Bot.pixs.length){var a=Bot.pixs.shift();Bot.canvasClick(a[0],a[1],a[2])}else Bot.setState("No points, yay!")};alert=function(){location.reload()};Bot.canvasMove=function(a,b){var d={bubbles:!0,cancelable:!0,button:1,clientX:0,clientY:0};Bot.canvasEvent("mousedown",d);d.clientY=b;d.clientX=a;Bot.canvasEvent("mousemove",d);Bot.canvasEvent("mouseup",d)};Bot.canvasMoveTo=function(a,b){Bot.canvasMove(1E4,1E4);Bot.canvasMove(-40-a,-149-b)};Bot.getImageData=function(){return Bot.ctx.getImageData(0,
1,795,400).data};Bot.getColor=function(a,b){return"rgb("+a[b]+", "+a[b+1]+", "+a[b+2]+")"};Bot.getFullData=function(){Bot.pixs=[];Bot.pixs=Bot.pixs.concat(Bot.getData(0),Bot.getData(795)).sort(function(a,b){return a[1]-b[1]}).sort(function(a,b){return a[0]-b[0]});Bot.setState("Dots left:"+Bot.pixs.length);return Bot.pixs.length};Bot.getData=function(a){Bot.resetZoom();Bot.canvasMoveTo(a,0);var b=Bot.getImageData();Bot.ctx.drawImage(Bot.img,-a,1);for(var d=Bot.getImageData(),e=[],c=0;c<b.length;c+=
4){var f=a+c/4%795,g=~~(c/4/795);Bot.getColor(b,c)!==Bot.getColor(d,c)&&Bot.getColor(d,c)!==Bot.tc&&e.push([f,g,Bot.getColor(d,c),Bot.getColor(b,c)])}return e};Bot.resetZoom=function(){Bot.canvasEvent("mousewheel",{deltaY:1E5,deltaX:0,clientX:100,clientY:100})};Bot.init=function(){Bot.inited=1;Bot.getFullData();Bot.setState("Started.")};Bot.wait=setInterval(function(){!Bot.inited&&Bot.canvas?(Bot.ctx=Bot.canvas.getContext("2d"),Bot.init()):Bot.canvas&&document.querySelector(".Ttl__wait")?Bot.timer=
1:Bot.canvas?Bot.pts?Bot.inited&&Bot.canvas&&(Bot.pts--,Bot.draw()):(Bot.reload(),Bot.pts=30):Bot.canvas=document.querySelector("canvas")},1E3);Bot.reloadImage();console.log("Loaded")}window.loaded&&Bot();window.addEventListener("load",function(){window.loaded=1;var a=document.createElement("script");a.appendChild(document.createTextNode("("+Bot+")();"));(document.body||document.head||document.documentElement).appendChild(a)});
